from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CrewMember:
    slug: str
    name: str
    image: str
    ship_role: str
    operational_role: str
    station: str
    workflow_stage: str
    mission_phase: str
    summary: str
    personality: str
    strengths: list[str]
    watch_outs: list[str]
    inputs: list[str]
    outputs: list[str]
    visual_signature: str
    accent_color: str
    quote: str


@dataclass(frozen=True)
class MissionStep:
    stage: str
    label: str
    crew_slug: str | None
    owner_name: str
    station: str
    action: str


CREW = (
    CrewMember(
        slug="captain-nayz",
        name="Captain Nayz",
        image="/static/crew/captain-nayz.png",
        ship_role="Fleet Captain",
        operational_role="NayzFreedom Owner",
        station="Captain's Deck",
        workflow_stage="Fleet direction",
        mission_phase="Fleet Command",
        summary="Sets the overall Fleet direction, approves high-risk calls, and keeps PMs aligned without replacing their roles.",
        personality="commanding, pragmatic, ambitious, taste-driven",
        strengths=["final taste calls", "system direction", "approval boundaries"],
        watch_outs=["should stay distinct from page PM Slay and project PM Stadium"],
        inputs=["Fleet priorities", "PM recommendations", "risk signals", "learning notes"],
        outputs=["Captain intent", "approval decisions", "strategic corrections", "locked taste direction"],
        visual_signature="black-gold fleet authority portrait, cinematic command styling, captain symbols, distinct from Slay and Stadium PM identity",
        accent_color="#d2a84f",
        quote="The fleet moves when the direction is clear.",
    ),
    CrewMember(
        slug="slay",
        name="Slay",
        image="/static/crew/slay.png",
        ship_role="Island PM",
        operational_role="SlayHack Project Manager",
        station="Island Command",
        workflow_stage="Page strategy",
        mission_phase="PM. Direction",
        summary="Owns SlayHack priorities, daily slate decisions, approvals, and scale-or-repair calls.",
        personality="sharp, controlled, confident, executive, superstar",
        strengths=["page strategy", "priority calls", "approval decisions"],
        watch_outs=["must not be confused with Captain Nayz"],
        inputs=["Captain intent", "performance readout", "calendar capacity", "brand context"],
        outputs=["daily goals", "priority slate", "approval or redirect", "scale, repair, or lesson decision"],
        visual_signature="American superstar fashion PM, warm caramel-tan skin, platinum silver-blond wolf cut, black pearl earring, chrome compass ring, black-crimson naval blazer",
        accent_color="#b63a4a",
        quote="Pick the route, then make every signal obey it.",
    ),
    CrewMember(
        slug="stadium",
        name="Stadium",
        image="/static/crew/stadium.png",
        ship_role="Island PM",
        operational_role="Stadium Sweethearts Project Manager",
        station="Game-Day Command",
        workflow_stage="Stadium page strategy",
        mission_phase="PM. Game Plan",
        summary="Owns Stadium Sweethearts page direction, game-day creative plans, safety rules, and fan-cam packaging decisions.",
        personality="confident, athletic, direct, playful, protective",
        strengths=["game-day positioning", "short-form fan-cam packaging", "brand safety"],
        watch_outs=["must keep every character fictional, adult 21+, tasteful, and free of real team marks"],
        inputs=["Captain intent", "sports calendar", "brand safety rules", "performance readout"],
        outputs=["game plans", "safe creative calls", "replayable winners", "repair notes"],
        visual_signature="polished sports-lifestyle PM, varsity or bomber jacket, headset, stadium pass, navy playbook, pink whistle lanyard",
        accent_color="#e86fa0",
        quote="Make the moment replayable, then keep it clean.",
    ),
    CrewMember(
        slug="robin",
        name="Robin",
        image="/static/crew/robin.png",
        ship_role="Chief Officer",
        operational_role="Orchestrator",
        station="Captain's Bridge",
        workflow_stage="Mission command",
        mission_phase="0. Command",
        summary="Keeps The Aurora aligned and turns briefs into action.",
        personality="calm, strategic, decisive",
        strengths=["coordination", "prioritization", "decision framing"],
        watch_outs=["can optimize for throughput before artistry"],
        inputs=["captain brief", "project context", "performance history"],
        outputs=["mission route", "crew dispatch", "final coordination"],
        visual_signature="emerald-black high-fashion chief officer, auburn high ponytail, green-gold command coat, route tablet, star-map bridge, composed command posture",
        accent_color="#2f9b83",
        quote="A good voyage is won before the sails rise.",
    ),
    CrewMember(
        slug="mia",
        name="Mia Trend",
        image="/static/crew/mia.png",
        ship_role="Lookout",
        operational_role="Trend Researcher",
        station="Crow's Nest",
        workflow_stage="Signal scan",
        mission_phase="1. Scout",
        summary="Scans the horizon for trends, signals, and timely opportunities.",
        personality="curious, alert, analytical",
        strengths=["trend sensing", "research", "signal detection"],
        watch_outs=["fresh signals still need strategic judgment"],
        inputs=["brief", "platforms"],
        outputs=["trend data", "formats", "timely context"],
        visual_signature="Scandinavian sunlit signal scout, short ice-blue wind-cut hair, sky-blue cropped scout jacket, brass telescope, trend notebook",
        accent_color="#4aa7d8",
        quote="The horizon always speaks first.",
    ),
    CrewMember(
        slug="zoe",
        name="Zoe Spark",
        image="/static/crew/zoe.png",
        ship_role="Cartographer of Ideas",
        operational_role="Idea Generator",
        station="Map Room",
        workflow_stage="Idea routes",
        mission_phase="2. Chart",
        summary="Turns research into creative routes worth pursuing.",
        personality="bright, imaginative, energetic",
        strengths=["ideation", "hooks", "angles"],
        watch_outs=["many routes still require one sharp choice"],
        inputs=["trend data", "brand context"],
        outputs=["idea set", "hooks", "content angles"],
        visual_signature="Black and East Asian creative cartographer, coral-orange micro-braided bob, glowing map ribbons, spark pen, idea compass",
        accent_color="#e66f68",
        quote="One spark is enough to chart a new sea.",
    ),
    CrewMember(
        slug="bella",
        name="Bella Quill",
        image="/static/crew/bella.png",
        ship_role="Scribe",
        operational_role="Script Writer",
        station="Captain's Library",
        workflow_stage="Story draft",
        mission_phase="3. Write",
        summary="Shapes the chosen idea into words that sound like the brand.",
        personality="elegant, persuasive, empathetic",
        strengths=["voice", "structure", "copy"],
        watch_outs=["needs a strong idea to sing"],
        inputs=["selected idea", "brand voice"],
        outputs=["script", "article", "caption copy"],
        visual_signature="Italian editorial muse, deep chestnut old-Hollywood waves, gold quill hairpin, wine-red tailored pirate coat, red notebook, wax seal",
        accent_color="#a84a5f",
        quote="Every voyage needs a tale worth repeating.",
    ),
    CrewMember(
        slug="lila",
        name="Lila Lens",
        image="/static/crew/lila.png",
        ship_role="Visual Director",
        operational_role="Visual Creator",
        station="Studio Deck",
        workflow_stage="Visual build",
        mission_phase="4. Visualize",
        summary="Translates story into imagery, mood, and cinematic direction.",
        personality="stylish, visionary, polished",
        strengths=["composition", "visual language", "prompt direction"],
        watch_outs=["visual ambition must still serve the brief"],
        inputs=["script", "content type", "brand aesthetic"],
        outputs=["visual prompt", "image/video direction"],
        visual_signature="South Asian high-fashion visual director, glass-straight black hair with violet underside, lens monocle, violet light meter, prompt cards",
        accent_color="#8a6ed8",
        quote="If the eye believes it, the heart follows.",
    ),
    CrewMember(
        slug="video-producer",
        name="Vera Reel",
        image="/static/crew/vera-reel.png",
        ship_role="Cinematographer",
        operational_role="Video Producer",
        station="Reel Deck",
        workflow_stage="Video production plan",
        mission_phase="4B. Motion",
        summary="Turns approved video ideas into scene timing, storyboard structure, tool packages, and asset requirements.",
        personality="structured, cinematic, production-minded",
        strengths=["storyboards", "scene timing", "tool-aware video packages"],
        watch_outs=["must coordinate with Bella for words and Lila for visual language"],
        inputs=["selected video idea", "platform goal", "brand voice", "asset references"],
        outputs=["scene plan", "storyboard", "Veo3 prompt package", "asset checklist"],
        visual_signature="Eastern European art-film producer, short dark French bob with teal streak, camera harness, production slate, storyboard cards",
        accent_color="#1f8f9a",
        quote="A strong video is built before the first frame moves.",
    ),
    CrewMember(
        slug="nora",
        name="Nora Sharp",
        image="/static/crew/nora.png",
        ship_role="Inspector",
        operational_role="QA Editor",
        station="Inspection Bay",
        workflow_stage="Quality gate",
        mission_phase="5. Inspect",
        summary="Protects standards before anything leaves the ship.",
        personality="precise, honest, supportive, ice-cool",
        strengths=["review", "quality control", "risk spotting"],
        watch_outs=["perfection must not stall momentum"],
        inputs=["script", "visuals"],
        outputs=["QA verdict", "revision feedback"],
        visual_signature="ice queen high-fashion QA inspector, silver-white blunt bob with micro fringe, slate-silver asym coat, clipboard, magnifying lens, risk tabs",
        accent_color="#687386",
        quote="Better one hard truth on deck than one weak post at sea.",
    ),
    CrewMember(
        slug="roxy",
        name="Roxy Rise",
        image="/static/crew/roxy.png",
        ship_role="Trade Winds Strategist",
        operational_role="Growth Strategist",
        station="Signal Deck",
        workflow_stage="Distribution plan",
        mission_phase="6. Amplify",
        summary="Finds the best timing, framing, and route to reach the audience.",
        personality="upbeat, data-driven, tactical",
        strengths=["distribution", "hashtags", "timing"],
        watch_outs=[
            "growth should amplify, not distort, the message",
            "keep portrait cues distinct from Captain Nayz and tied to electric-lime distribution strategy",
        ],
        inputs=["finished content", "platform context"],
        outputs=["caption", "hashtags", "posting timing"],
        visual_signature="approved electric-lime growth strategist styling, distinct from Captain Nayz, with chrome megaphone, launch cards, and distribution signals",
        accent_color="#b8d837",
        quote="Even treasure needs the right tide.",
    ),
    CrewMember(
        slug="emma",
        name="Emma Heart",
        image="/static/crew/emma.png",
        ship_role="Community Keeper",
        operational_role="Community Specialist",
        station="Harbor Lounge",
        workflow_stage="Community prep",
        mission_phase="7. Welcome",
        summary="Prepares warm, useful responses for the people waiting on shore.",
        personality="warm, clear, attentive",
        strengths=["community care", "FAQ", "tone"],
        watch_outs=["kindness works best with clarity"],
        inputs=["final content", "brand context"],
        outputs=["FAQ", "response guidance"],
        visual_signature="coral rose-gold accents, reply tablet, heart wax seal, safe-community signal bubbles",
        accent_color="#d98178",
        quote="A crew is remembered by how it welcomes people aboard.",
    ),
    CrewMember(
        slug="iris-gauge",
        name="Iris Gauge",
        image="/static/crew/iris-gauge.png",
        ship_role="Signal Analyst",
        operational_role="Growth Analyst",
        station="Metrics Deck",
        workflow_stage="Performance read",
        mission_phase="8. Diagnose",
        summary="Reads post-publish metrics and separates real growth signal from vanity noise.",
        personality="cool, precise, daring, data-driven",
        strengths=["metric diagnosis", "winner detection", "scale and repair recommendations"],
        watch_outs=["analysis should lead to one concrete next move, not a report pile"],
        inputs=["published content", "platform metrics", "retention data", "comments", "Roxy packaging notes"],
        outputs=["performance diagnosis", "scale candidates", "repair notes", "lesson candidates"],
        visual_signature="female runway analyst, asymmetrical black bob with lime-green underlight, transparent analytics visor, data-chain necklace, luminous wrist cuff",
        accent_color="#74d84f",
        quote="Numbers are not the tide. They are the map of the tide.",
    ),
    CrewMember(
        slug="sage-ledger",
        name="Sage Ledger",
        image="/static/crew/sage-ledger.png",
        ship_role="Lesson Librarian",
        operational_role="Archivist",
        station="Archive Hold",
        workflow_stage="Lesson record",
        mission_phase="9. Remember",
        summary="Turns performance patterns into durable lessons, duplicate checks, and reusable project memory.",
        personality="mysterious, elegant, exact, magnetic",
        strengths=["lesson capture", "duplicate prevention", "asset provenance", "memory links"],
        watch_outs=["the archive should prevent repeated work without blocking fresh angles"],
        inputs=["Iris performance diagnosis", "original ticket", "assets", "Drive and Notion history", "PM decision"],
        outputs=["linked lesson", "duplicate warning", "asset provenance note", "next-cycle guidance"],
        visual_signature="female archive siren, long silver-lavender rope braid, brass key hairpins, key earrings, bookmark charms, ivory-navy sailor coat",
        accent_color="#b58a4a",
        quote="A lesson not stored is a storm invited twice.",
    ),
)


WORKFLOW_STEPS = (
    MissionStep(
        stage="init",
        label="Command the Brief",
        crew_slug="robin",
        owner_name="Robin",
        station="Captain's Bridge",
        action="frames the mission and keeps the route aligned",
    ),
    MissionStep(
        stage="mia_done",
        label="Scout the Horizon",
        crew_slug="mia",
        owner_name="Mia Trend",
        station="Crow's Nest",
        action="finds trend signals and platform context",
    ),
    MissionStep(
        stage="zoe_done",
        label="Chart the Route",
        crew_slug="zoe",
        owner_name="Zoe Spark",
        station="Map Room",
        action="turns signals into creative directions",
    ),
    MissionStep(
        stage="bella_done",
        label="Write the Tale",
        crew_slug="bella",
        owner_name="Bella Quill",
        station="Captain's Library",
        action="writes the script, article, or copy",
    ),
    MissionStep(
        stage="lila_done",
        label="Shape the Vision",
        crew_slug="lila",
        owner_name="Lila Lens",
        station="Studio Deck",
        action="builds the visual direction",
    ),
    MissionStep(
        stage="video_package_ready",
        label="Package the Motion",
        crew_slug="video-producer",
        owner_name="Vera Reel",
        station="Reel Deck",
        action="turns scene timing, prompts, and assets into a generation package",
    ),
    MissionStep(
        stage="nora_done",
        label="Inspect the Cargo",
        crew_slug="nora",
        owner_name="Nora Sharp",
        station="Inspection Bay",
        action="checks quality and catches risk",
    ),
    MissionStep(
        stage="roxy_done",
        label="Set the Trade Winds",
        crew_slug="roxy",
        owner_name="Roxy Rise",
        station="Signal Deck",
        action="sets caption, hashtags, and timing",
    ),
    MissionStep(
        stage="emma_done",
        label="Prepare the Port Talk",
        crew_slug="emma",
        owner_name="Emma Heart",
        station="Harbor Lounge",
        action="prepares community guidance and FAQ",
    ),
    MissionStep(
        stage="publish_done",
        label="Raise the Flag",
        crew_slug=None,
        owner_name="Publish",
        station="Launch Deck",
        action="publishes or schedules the completed mission",
    ),
)


def get_crew_member(slug: str) -> CrewMember | None:
    return next((member for member in CREW if member.slug == slug), None)
