from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


@dataclass
class IdeaDraft:
    """Ephemeral idea generated by IdeaPlannerAgent before KS storage."""

    title: str
    hook: str
    angle: str
    content_type: str
    source_signal_uids: list[str] = field(default_factory=list)


class IdeaPlanJobStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class IdeaPlanJob(BaseModel):
    """Persisted job record for a single IdeaPlanner run."""

    job_id: str
    page_slug: str
    triggered_by: str
    created_at: datetime = Field(default_factory=datetime.now)
    status: IdeaPlanJobStatus = IdeaPlanJobStatus.PENDING
    ideas_generated: int = 0
    ideas_stored: int = 0
    ideas_skipped: int = 0
    signals_used: int = 0
    digest_path: Optional[str] = None
    error: Optional[str] = None
